version: "3.8"

networks:
  minio-network:
    external: true

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: abhinavzweb
      MINIO_ROOT_PASSWORD: ksQbZ6Qpex
      MINIO_SERVER_URL: https://minio1.supa.abhnv.xyz
    command: server /data --console-address ":9090"
    networks:
      - minio-network
  # nginx:
  #   image: "jc21/nginx-proxy-manager:latest"
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-data:/data
  #     - ./nginx-letsencrypt:/etc/letsencrypt
